### ISSUE TITLE
Have you tryed any other  Hyperparameter？

### ISSUE THREAD

**Issue by 578123043** [THUcqb/KOBE#13]
It seems that the Transformer-encoder is not more important than Decoder.
So why you use a 6 encoder layers  but only 2 decoder layers ?
Does it help to improve performance?

**Comment by qibinc** [comment]
Hi @578123043 ,

You're right. The encoder is equally important as the decoder.
However, one important thing to notice is that more decoder layers make the decoding much **slower** because the decoding is done auto-regressively, while the encoding needs to be done only once and is much faster.
We did try more decoder layers (1, 2, 3, 6) and found the improvement is not very significant after 2. Since the encoding is fast, we keep 6 layers for the encoder. If you want to further explore this by yourself, you can change `enc_num_layers` and `dec_num_layers` in the config files and run different experiment with ease.
