### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by pangxijie** [THUcqb/KOBE#20]
Hi, i am interesting in this paper. But I am a little confused about the dataset for experiment. I can get product title in TaoBao easily, but can not find product description. So I am confused what should I do to get description especially personalized description for ground-truth like your dataset.

**Comment by qibinc** [comment]
Hi @pangxijie ,

Thanks for being interested in this work! Really good question about the dataset. First, I want to point out that we provide more detailed descriptions about dataset in the Appendix, especially on the personalization part. If you haven't check that out, please have a look at that. 

If you still have questions:

#### 1 Get descriptions

We don't get descriptions from the product page (https://detail.tmall.com/item.htm). These contents are provided by sellers, in different formats and it's inconvenient for Taobao to change and improve. 

Therefore, we focus on contents provided by the platform. To see them, you need to use app version of Taobao, where you can see various articles written by content producers on the platform ("淘宝达人" in Chinese). For example, please see https://world.taobao.com/qingdan-amp/223269237051.htm . In these articles, we pair the descriptions with the items mentioned.

#### 2 Get personalization

We introduce how we get ground truth of personalization in the Appendix. Briefly, we counted the majority user category that have clicked / stayed on a description and use that as the personalization label, so that during generation, we specify a user category and the generated description will satisfy that category of users.

**Comment by pangxijie** [comment]
Thank you @qibinc . I have read the Appendix and I learned the method for preprocessing. I got into trouble when I tried to build a dataset for other platform. Thank your for your patient answer!
