### ISSUE TITLE
Question on the decoding behavior 

### ISSUE THREAD

**Issue by canjiali** [THUcqb/KOBE#24]
Hi Qibin,

Thanks for the nice work. I have a question on the Transformer decoding behavior. I noticed that during training the whole ground truth is fed into the decoder, allowing the tokens in step $i$ to attend on the previous $i-1$ tokens as in the self-attention layer. However, while in the inference stage, you only feed one token for step $i$, i.e. the output token from step $i-1$, as follows:

https://github.com/THUDM/KOBE/blob/master/core/models/tensor2tensor.py#L369

I guess that the self-attention layer loses its effectiveness at this time. Why don't we feed the outputs from step 0 to step $i-1$ for decoding step $i$ as we do in the training phase?

**Comment by qibinc** [comment]
Hi @StKlaas ,

Thanks for checking out the code! Different from training, the inference stage is done auto-regressively. The decoded token is fed to the next input step by step. There is an important trick here:

https://github.com/THUDM/KOBE/blob/7bbf05f490bbe81a7da56c16ebe1f6b31cf54a34/core/models/transformer.py#L501

Previous decoded outputs are stored in `self.state["cache"]`. Further, the hidden states of previous steps won't be computed again, since they don't depend on the later time-steps. In a word, we only feed one token at step $i$ because the previous tokens are stored in cache of `TransformerDecoder`. (`TransformerDecoder.forward` is stateful in inference stage)

I think this caching trick is common in most modern Transformer implementations.

Hope this helps!

**Comment by canjiali** [comment]
The explanation helps a lot! I'm glad to know that! 
In other words, the cache is stored once and won't be used in the training phase. However, in the inference phase, it is updated step by step and fetched by the decoder. Is it right?
