### ISSUE TITLE
Building Dataset In English Language

### ISSUE THREAD

**Issue by nikhila99** [THUcqb/KOBE#33]
Hi, I have data consisting of product titles, descriptions, and categories of a marketplace in English. Would be kind enough if you could help me by explaining how to prepare a proper datasets/format of the datasets for that data.
Thankyou in advance.

**Comment by qibinc** [comment]
Hi @nikhila99 ,

Thanks for reaching out. The full KOBE pipeline requires a knowledge base where relevant information about the product title can be retrieved and fed into the model. Because you only have the category information, I suggest that you look into a general seq2seq lib such as https://github.com/pytorch/fairseq and train a conditional seq2seq model. Specifically, you can simply treat the category tokens as special words and prepend them to the source sequence, and you can run the normal seq2seq training pipeline.

**Comment by nikhila99** [comment]
Hi @qibinc,
I find KOBE as the perfect suitable solution for product description generation use-case.

Please help me understand what is the knowledge base I require? Could you explain what else data I need to build a dataset; if possible I will try to create or get that data. Also, please check if this link https://github.com/IBM/build-knowledge-base-with-domain-specific-documents/blob/master/README.md can help me out for the same? 

I would be glad if you help me create the dataset, and advise any changes that I need to make in code after changing dataset.
Thanks in advance.
