### ISSUE TITLE
biattention code

### ISSUE THREAD

**Issue by tumanshu** [THUcqb/KOBE#35]

**Comment by tumanshu** [comment]
in your paper bi-attention :[h;u~;h\*u~;h\*h~]
in your code transformer.py line 170 is [h;u~;h\*u~;h~\*u~]

**Comment by qibinc** [comment]
Hi @tumanshu ,

Thanks a lot for your contribution. You're right on this issue. Actually, we borrowed the implementation of bi-attention from https://github.com/hotpotqa/hotpot/blob/master/model.py#L196-L220. And it's indeed different from the original BiDAF paper. 

My memory of the past experiments of this work has been a bit rusted by now, but I don't think this part of BiDAF can lead to a major difference in the results. As long as both `h`, `u` are in the representation, the two representations can be effectively fused. The specific formulation was hand-crafted by the BiDAF authors based on the results on their dataset anyway.

In the end, I really appreciated your contribution. Once done with my current work, I will try to either a. update the results with the fixed code or b. update the formulation in paper, based on which one turns out to be better.
