### ISSUE TITLE
Named entity to match product title with knowledge graph

### ISSUE THREAD

**Issue by hdvvip** [THUcqb/KOBE#37]
Hi,
Thank you so much for a great paper and for sharing the code!

I read the paper and have a small confusion.
https://arxiv.org/pdf/1903.12457.pdf 

On page 5, you said "Formally, given a product title x = (x1, x2, . . . , xn), we match each word xi to a
named entity vi ∈ V, which should be a vertex in the knowledge graph."
Could you please explain what are those named entity?
What is the process you used to match the word to the given named entity vi
For Chinese, you used CN-DBPedia. How about English? Which English knowledge graph you recommend using?

Thank you so much again!

**Comment by qibinc** [comment]
Hi @hdvvip ,

Thanks for your interest in this work. The process for "matching words to a given named entity in a knowledge base" is called _entity linking_. For English, I suggest you look at dbpedia which comes with a great [entity linking tool](https://github.com/dbpedia-spotlight/dbpedia-spotlight-model). You can also use wikidata which is the most popular choice for English knowledge base.

Apart from this, because our work is pretty old, I suggest you also look at [this more recent work](https://arxiv.org/pdf/2005.11401), where they did experiments in English and is probably more suitable for your task.

**Comment by hdvvip** [comment]
Great answer! Thank you so much!
