### ISSUE TITLE
how long does the training process last?Could  u please provide the training result?

### ISSUE THREAD

**Issue by jiangliqin** [THUcqb/KOBE#43]

**Comment by qibinc** [comment]
Hi @jiangliqin ,

Thanks for your attention. The training process of a single model typically last for 12-24 hours on a modern GPU. And the model with knowledge usually takes longer. Unfortunately, I can no longer provide the training results or trained models of the exact runs since it's been more than 2 years. However, I'm planning to update the code with the latest dependency, re-train the models and release the weights once and for all. Please stay tuned!

**Comment by jiangliqin** [comment]
ok,now i'm training in the 4*v100 GPUS.i'm greatly appreciate for your updated code.

**Comment by qibinc** [comment]
Hi @jiangliqin ,

We have rewritten this codebase and significantly improved the installation, code quality, reproducibility and visualization. Here is a screenshot of the KOBE-v2's training progress, in case your are still interested:

![image](https://user-images.githubusercontent.com/22570685/147371058-1cbff91a-8dd2-42a4-bde3-08dbcec83446.png)

Best,
